export const CountryCodeList = [
  {
    EnName: 'Albania',
    Name: '阿尔巴尼亚',
    IOS2: 'AL',
    IOS3: 'ALB',
    Code: '355',
  },
  {
    EnName: 'Algeria',
    Name: '阿尔及利亚',
    IOS2: 'DZ',
    IOS3: 'DZA',
    Code: '213',
  },
  {
    EnName: 'Afghanistan',
    Name: '阿富汗',
    IOS2: 'AF',
    IOS3: 'AFG',
    Code: '93',
  },
  {
    EnName: 'Argentina',
    Name: '阿根廷',
    IOS2: 'AR',
    IOS3: 'ARG',
    Code: '54',
  },
  {
    EnName: 'United Arab Emirates',
    Name: '阿拉伯联合酋长国',
    IOS2: 'AE',
    IOS3: 'ARE',
    Code: '971',
  },
  {
    EnName: 'Aruba', Name: '阿鲁巴', IOS2: 'AW', IOS3: 'ABW', Code: '297',
  },
  {
    EnName: 'Oman',
    Name: '阿曼',
    IOS2: 'OM',
    IOS3: 'OMN',
    Code: '968',
  },
  {
    EnName: 'Azerbaijan', Name: '阿塞拜疆', IOS2: 'AZ', IOS3: 'AZE', Code: '994',
  },
  {
    EnName: 'Egypt',
    Name: '埃及',
    IOS2: 'EG',
    IOS3: 'EGY',
    Code: '20',
  },
  {
    EnName: 'Ethiopia', Name: '埃塞俄比亚', IOS2: 'ET', IOS3: 'ETH', Code: '251',
  },
  {
    EnName: 'Ireland',
    Name: '爱尔兰',
    IOS2: 'IE',
    IOS3: 'IRL',
    Code: '353',
  },
  {
    EnName: 'Estonia', Name: '爱沙尼亚', IOS2: 'EE', IOS3: 'EST', Code: '372',
  },
  {
    EnName: 'Andorra',
    Name: '安道尔',
    IOS2: 'AD',
    IOS3: 'AND',
    Code: '376',
  },
  {
    EnName: 'Angola', Name: '安哥拉', IOS2: 'AO', IOS3: 'AGO', Code: '244',
  },
  {
    EnName: 'Anguilla',
    Name: '安圭拉',
    IOS2: 'AI',
    IOS3: 'AIA',
    Code: '1264',
  },
  {
    EnName: 'Antigua and Barbuda',
    Name: '安提瓜和巴布达',
    IOS2: 'AG',
    IOS3: 'ATG',
    Code: '1268',
  },
  {
    EnName: 'Austria', Name: '奥地利', IOS2: 'AT', IOS3: 'AUT', Code: '43',
  },
  {
    EnName: 'Australia',
    Name: '澳大利亚',
    IOS2: 'AU',
    IOS3: 'AUS',
    Code: '61',
  },
  {
    EnName: 'Barbados',
    Name: '巴巴多斯',
    IOS2: 'BB',
    IOS3: 'BRB',
    Code: '1246',
  },
  {
    EnName: 'Papua New Guinea',
    Name: '巴布亚新几内亚',
    IOS2: 'PG',
    IOS3: 'PNG',
    Code: '675',
  },
  {
    EnName: 'Bahamas', Name: '巴哈马', IOS2: 'BS', IOS3: 'BHS', Code: '1242',
  },
  {
    EnName: 'Pakistan',
    Name: '巴基斯坦',
    IOS2: 'PK',
    IOS3: 'PAK',
    Code: '92',
  },
  {
    EnName: 'Paraguay', Name: '巴拉圭', IOS2: 'PY', IOS3: 'PRY', Code: '595',
  },
  {
    EnName: 'Palestine',
    Name: '巴勒斯坦',
    IOS2: 'PS',
    IOS3: 'PSE',
    Code: '970',
  },
  {
    EnName: 'Bahrain', Name: '巴林', IOS2: 'BH', IOS3: 'BHR', Code: '973',
  },
  {
    EnName: 'Panama',
    Name: '巴拿马',
    IOS2: 'PA',
    IOS3: 'PAN',
    Code: '507',
  },
  {
    EnName: 'Brazil', Name: '巴西', IOS2: 'BR', IOS3: 'BRA', Code: '55',
  },
  {
    EnName: 'Belarus',
    Name: '白俄罗斯',
    IOS2: 'BY',
    IOS3: 'BLR',
    Code: '375',
  },
  {
    EnName: 'Bermuda', Name: '百慕大', IOS2: 'BM', IOS3: 'BMU', Code: '1441',
  },
  {
    EnName: 'Bulgaria',
    Name: '保加利亚',
    IOS2: 'BG',
    IOS3: 'BGR',
    Code: '359',
  },
  {
    EnName: 'Northern Mariana Islands',
    Name: '北马里亚纳群岛',
    IOS2: 'MP',
    IOS3: 'MNP',
    Code: '1670',
  },
  {
    EnName: 'Benin', Name: '贝宁', IOS2: 'BJ', IOS3: 'BEN', Code: '229',
  },
  {
    EnName: 'Belgium',
    Name: '比利时',
    IOS2: 'BE',
    IOS3: 'BEL',
    Code: '32',
  },
  {
    EnName: 'Iceland', Name: '冰岛', IOS2: 'IS', IOS3: 'ISL', Code: '354',
  },
  {
    EnName: 'Puerto Rico',
    Name: '波多黎各',
    IOS2: 'PR',
    IOS3: 'PRI',
    Code: '1787',
  },
  {
    EnName: 'Poland',
    Name: '波兰',
    IOS2: 'PL',
    IOS3: 'POL',
    Code: '48',
  },
  {
    EnName: 'Bosnia and Herzegovina',
    Name: '波斯尼亚和黑塞哥维那',
    IOS2: 'BA',
    IOS3: 'BIH',
    Code: '387',
  },
  {
    EnName: 'Bolivia', Name: '玻利维亚', IOS2: 'BO', IOS3: 'BOL', Code: '591',
  },
  {
    EnName: 'Belize',
    Name: '伯利兹',
    IOS2: 'BZ',
    IOS3: 'BLZ',
    Code: '501',
  },
  {
    EnName: 'Botswana', Name: '博茨瓦纳', IOS2: 'BW', IOS3: 'BWA', Code: '267',
  },
  {
    EnName: 'Bhutan',
    Name: '不丹',
    IOS2: 'BT',
    IOS3: 'BTN',
    Code: '975',
  },
  {
    EnName: 'Burkina Faso',
    Name: '布基纳法索',
    IOS2: 'BF',
    IOS3: 'BFA',
    Code: '226',
  },
  {
    EnName: 'Burundi',
    Name: '布隆迪',
    IOS2: 'BI',
    IOS3: 'BDI',
    Code: '257',
  },
  {
    EnName: 'Equatorial Guinea',
    Name: '赤道几内亚',
    IOS2: 'GQ',
    IOS3: 'GNQ',
    Code: '240',
  },
  {
    EnName: 'Denmark', Name: '丹麦', IOS2: 'DK', IOS3: 'DNK', Code: '45',
  },
  {
    EnName: 'Germany',
    Name: '德国',
    IOS2: 'DE',
    IOS3: 'DEU',
    Code: '49',
  },
  {
    EnName: 'East Timor', Name: '东帝汶', IOS2: 'TL', IOS3: 'TLS', Code: '670',
  },
  {
    EnName: 'Togo',
    Name: '多哥',
    IOS2: 'TG',
    IOS3: 'TGO',
    Code: '228',
  },
  {
    EnName: 'Dominica',
    Name: '多米尼加',
    IOS2: 'DM',
    IOS3: 'DMA',
    Code: '1767',
  },
  {
    EnName: 'Dominican Republic',
    Name: '多明尼加共和国',
    IOS2: 'DO',
    IOS3: 'DOM',
    Code: '1809',
  },
  {
    EnName: 'Russia', Name: '俄国', IOS2: 'RU', IOS3: 'RUS', Code: '7',
  },
  {
    EnName: 'Ecuador',
    Name: '厄瓜多尔',
    IOS2: 'EC',
    IOS3: 'ECU',
    Code: '593',
  },
  {
    EnName: 'Eritrea', Name: '厄立特里亚', IOS2: 'ER', IOS3: 'ERI', Code: '291',
  },
  {
    EnName: 'France',
    Name: '法国',
    IOS2: 'FR',
    IOS3: 'FRA',
    Code: '33',
  },
  {
    EnName: 'Faroe Islands',
    Name: '法罗群岛',
    IOS2: 'FO',
    IOS3: 'FRO',
    Code: '298',
  },
  {
    EnName: 'French Polynesia',
    Name: '法属波利尼西亚',
    IOS2: 'PF',
    IOS3: 'PYF',
    Code: '689',
  },
  {
    EnName: 'Vatican',
    Name: '梵帝冈',
    IOS2: 'VA',
    IOS3: 'VAT',
    Code: '379',
  },
  {
    EnName: 'Philippines', Name: '菲律宾', IOS2: 'PH', IOS3: 'PHL', Code: '63',
  },
  {
    EnName: 'Fiji',
    Name: '斐济',
    IOS2: 'FJ',
    IOS3: 'FJI',
    Code: '679',
  },
  {
    EnName: 'Finland', Name: '芬兰', IOS2: 'FI', IOS3: 'FIN', Code: '358',
  },
  {
    EnName: 'Cape Verde',
    Name: '佛得角',
    IOS2: 'CV',
    IOS3: 'CPV',
    Code: '238',
  },
  {
    EnName: 'Falkland Islands',
    Name: '福克兰群岛',
    IOS2: 'FK',
    IOS3: 'FLK',
    Code: '500',
  },
  {
    EnName: 'Gambia',
    Name: '冈比亚',
    IOS2: 'GM',
    IOS3: 'GMB',
    Code: '220',
  },
  {
    EnName: 'Republic of the Congo',
    Name: '刚果民主共和国',
    IOS2: 'CG',
    IOS3: 'COG',
    Code: '242',
  },
  {
    EnName: 'Democratic Republic of the Congo',
    Name: '刚果民主共和国',
    IOS2: 'CD',
    IOS3: 'COD',
    Code: '243',
  },
  {
    EnName: 'Colombia',
    Name: '哥伦比亚',
    IOS2: 'CO',
    IOS3: 'COL',
    Code: '57',
  },
  {
    EnName: 'Costa Rica',
    Name: '哥斯达黎加',
    IOS2: 'CR',
    IOS3: 'CRI',
    Code: '506',
  },
  {
    EnName: 'Grenada',
    Name: '格林纳达',
    IOS2: 'GD',
    IOS3: 'GRD',
    Code: '1473',
  },
  {
    EnName: 'Greenland', Name: '格陵兰', IOS2: 'GL', IOS3: 'GRL', Code: '299',
  },
  {
    EnName: 'Georgia',
    Name: '格鲁吉亚',
    IOS2: 'GE',
    IOS3: 'GEO',
    Code: '995',
  },
  {
    EnName: 'Guam', Name: '关岛', IOS2: 'GU', IOS3: 'GUM', Code: '1671',
  },
  {
    EnName: 'Guyana',
    Name: '圭亚那',
    IOS2: 'GY',
    IOS3: 'GUY',
    Code: '592',
  },
  {
    EnName: 'Kazakhstan', Name: '哈萨克斯坦', IOS2: 'KZ', IOS3: 'KAZ', Code: '7',
  },
  {
    EnName: 'Haiti',
    Name: '海地',
    IOS2: 'HT',
    IOS3: 'HTI',
    Code: '509',
  },
  {
    EnName: 'South Korea',
    Name: '韩国',
    IOS2: 'KR',
    IOS3: 'KOR',
    Code: '82',
  },
  {
    EnName: 'Netherlands',
    Name: '荷兰',
    IOS2: 'NL',
    IOS3: 'NLD',
    Code: '31',
  },
  {
    EnName: 'Netherlands Antilles',
    Name: '荷属安的列斯',
    IOS2: 'AN',
    IOS3: 'ANT',
    Code: '599',
  },
  {
    EnName: 'Montenegro', Name: '黑山', IOS2: 'ME', IOS3: 'MNE', Code: '382',
  },
  {
    EnName: 'Honduras',
    Name: '洪都拉斯',
    IOS2: 'HN',
    IOS3: 'HND',
    Code: '504',
  },
  {
    EnName: 'Kiribati', Name: '基里巴斯', IOS2: 'KI', IOS3: 'KIR', Code: '686',
  },
  {
    EnName: 'Djibouti',
    Name: '吉布提',
    IOS2: 'DJ',
    IOS3: 'DJI',
    Code: '253',
  },
  {
    EnName: 'Kyrgyzstan',
    Name: '吉尔吉斯斯坦',
    IOS2: 'KG',
    IOS3: 'KGZ',
    Code: '996',
  },
  {
    EnName: 'Guinea', Name: '几内亚', IOS2: 'GN', IOS3: 'GIN', Code: '224',
  },
  {
    EnName: 'Canada',
    Name: '加拿大',
    IOS2: 'CA',
    IOS3: 'CAN',
    Code: '1',
  },
  {
    EnName: 'Ghana', Name: '加纳', IOS2: 'GH', IOS3: 'GHA', Code: '233',
  },
  {
    EnName: 'Gabon',
    Name: '加蓬',
    IOS2: 'GA',
    IOS3: 'GAB',
    Code: '241',
  },
  {
    EnName: 'Cambodia',
    Name: '柬埔寨',
    IOS2: 'KH',
    IOS3: 'KHM',
    Code: '855',
  },
  {
    EnName: 'Czech Republic',
    Name: '捷克共和国',
    IOS2: 'CZ',
    IOS3: 'CZE',
    Code: '420',
  },
  {
    EnName: 'Zimbabwe', Name: '津巴布韦', IOS2: 'ZW', IOS3: 'ZWE', Code: '263',
  },
  {
    EnName: 'Cameroon',
    Name: '喀麦隆',
    IOS2: 'CM',
    IOS3: 'CMR',
    Code: '237',
  },
  {
    EnName: 'Qatar',
    Name: '卡塔尔',
    IOS2: 'QA',
    IOS3: 'QAT',
    Code: '974',
  },
  {
    EnName: 'Cayman Islands',
    Name: '开曼群岛',
    IOS2: 'KY',
    IOS3: 'CYM',
    Code: '1345',
  },
  {
    EnName: 'Cocos Islands',
    Name: '科科斯群岛',
    IOS2: 'CC',
    IOS3: 'CCK',
    Code: '61',
  },
  {
    EnName: 'Comoros', Name: '科摩罗', IOS2: 'KM', IOS3: 'COM', Code: '269',
  },
  {
    EnName: 'Kuwait',
    Name: '科威特',
    IOS2: 'KW',
    IOS3: 'KWT',
    Code: '965',
  },
  {
    EnName: 'Croatia', Name: '克罗地亚', IOS2: 'HR', IOS3: 'HRV', Code: '385',
  },
  {
    EnName: 'Kenya',
    Name: '肯尼亚',
    IOS2: 'KE',
    IOS3: 'KEN',
    Code: '254',
  },
  {
    EnName: 'Cook Islands',
    Name: '库克群岛',
    IOS2: 'CK',
    IOS3: 'COK',
    Code: '682',
  },
  {
    EnName: 'Latvia', Name: '拉脱维亚', IOS2: 'LV', IOS3: 'LVA', Code: '371',
  },
  {
    EnName: 'Lesotho',
    Name: '莱索托',
    IOS2: 'LS',
    IOS3: 'LSO',
    Code: '266',
  },
  {
    EnName: 'Laos', Name: '老挝', IOS2: 'LA', IOS3: 'LAO', Code: '856',
  },
  {
    EnName: 'Lebanon',
    Name: '黎巴嫩',
    IOS2: 'LB',
    IOS3: 'LBN',
    Code: '961',
  },
  {
    EnName: 'Lithuania', Name: '立陶宛', IOS2: 'LT', IOS3: 'LTU', Code: '370',
  },
  {
    EnName: 'Liberia',
    Name: '利比里亚',
    IOS2: 'LR',
    IOS3: 'LBR',
    Code: '231',
  },
  {
    EnName: 'Libya',
    Name: '利比亚',
    IOS2: 'LY',
    IOS3: 'LBY',
    Code: '218',
  },
  {
    EnName: 'Liechtenstein',
    Name: '列支敦士登',
    IOS2: 'LI',
    IOS3: 'LIE',
    Code: '423',
  },
  {
    EnName: 'Reunion', Name: '留尼汪', IOS2: 'RE', IOS3: 'REU', Code: '262',
  },
  {
    EnName: 'Luxembourg',
    Name: '卢森堡',
    IOS2: 'LU',
    IOS3: 'LUX',
    Code: '352',
  },
  {
    EnName: 'Rwanda', Name: '卢旺达', IOS2: 'RW', IOS3: 'RWA', Code: '250',
  },
  {
    EnName: 'Romania',
    Name: '罗马尼亚',
    IOS2: 'RO',
    IOS3: 'ROU',
    Code: '40',
  },
  {
    EnName: 'Madagascar',
    Name: '马达加斯加',
    IOS2: 'MG',
    IOS3: 'MDG',
    Code: '261',
  },
  {
    EnName: 'Maldives', Name: '马尔代夫', IOS2: 'MV', IOS3: 'MDV', Code: '960',
  },
  {
    EnName: 'Malta',
    Name: '马耳他',
    IOS2: 'MT',
    IOS3: 'MLT',
    Code: '356',
  },
  {
    EnName: 'Malawi', Name: '马拉维', IOS2: 'MW', IOS3: 'MWI', Code: '265',
  },
  {
    EnName: 'Malaysia',
    Name: '马来西亚',
    IOS2: 'MY',
    IOS3: 'MYS',
    Code: '60',
  },
  {
    EnName: 'Mali', Name: '马里', IOS2: 'ML', IOS3: 'MLI', Code: '223',
  },
  {
    EnName: 'Macedonia',
    Name: '马其顿',
    IOS2: 'MK',
    IOS3: 'MKD',
    Code: '389',
  },
  {
    EnName: 'Marshall Islands',
    Name: '马绍尔群岛',
    IOS2: 'MH',
    IOS3: 'MHL',
    Code: '692',
  },
  {
    EnName: 'Mayotte', Name: '马约特', IOS2: 'YT', IOS3: 'MYT', Code: '262',
  },
  {
    EnName: 'Mauritius',
    Name: '毛里求斯',
    IOS2: 'MU',
    IOS3: 'MUS',
    Code: '230',
  },
  {
    EnName: 'Mauritania',
    Name: '毛里塔尼亚',
    IOS2: 'MR',
    IOS3: 'MRT',
    Code: '222',
  },
  {
    EnName: 'United States',
    Name: '美国',
    IOS2: 'US',
    IOS3: 'USA',
    Code: '1',
  },
  {
    EnName: 'American Samoa',
    Name: '美属萨摩亚',
    IOS2: 'AS',
    IOS3: 'ASM',
    Code: '1684',
  },
  {
    EnName: 'U.S. Virgin Islands',
    Name: '美属维尔京群岛',
    IOS2: 'VI',
    IOS3: 'VIR',
    Code: '1340',
  },
  {
    EnName: 'Mongolia', Name: '蒙古', IOS2: 'MN', IOS3: 'MNG', Code: '976',
  },
  {
    EnName: 'Montserrat',
    Name: '蒙特塞拉特',
    IOS2: 'MS',
    IOS3: 'MSR',
    Code: '1664',
  },
  {
    EnName: 'Bangladesh', Name: '孟加拉国', IOS2: 'BD', IOS3: 'BGD', Code: '880',
  },
  {
    EnName: 'Peru',
    Name: '秘鲁',
    IOS2: 'PE',
    IOS3: 'PER',
    Code: '51',
  },
  {
    EnName: 'Micronesia',
    Name: '密克罗尼西亚',
    IOS2: 'FM',
    IOS3: 'FSM',
    Code: '691',
  },
  {
    EnName: 'Myanmar', Name: '缅甸', IOS2: 'MM', IOS3: 'MMR', Code: '95',
  },
  {
    EnName: 'Moldova',
    Name: '摩尔多瓦',
    IOS2: 'MD',
    IOS3: 'MDA',
    Code: '373',
  },
  {
    EnName: 'Morocco', Name: '摩洛哥', IOS2: 'MA', IOS3: 'MAR', Code: '212',
  },
  {
    EnName: 'Monaco',
    Name: '摩纳哥',
    IOS2: 'MC',
    IOS3: 'MCO',
    Code: '377',
  },
  {
    EnName: 'Mozambique', Name: '莫桑比克', IOS2: 'MZ', IOS3: 'MOZ', Code: '258',
  },
  {
    EnName: 'Mexico',
    Name: '墨西哥',
    IOS2: 'MX',
    IOS3: 'MEX',
    Code: '52',
  },
  {
    EnName: 'Namibia',
    Name: '纳米比亚',
    IOS2: 'NA',
    IOS3: 'NAM',
    Code: '264',
  },
  {
    EnName: 'South Africa',
    Name: '南非',
    IOS2: 'ZA',
    IOS3: 'ZAF',
    Code: '27',
  },
  {
    EnName: 'South Sudan', Name: '南苏丹', IOS2: 'SS', IOS3: 'SSD', Code: '211',
  },
  {
    EnName: 'Nauru',
    Name: '瑙鲁',
    IOS2: 'NR',
    IOS3: 'NRU',
    Code: '674',
  },
  {
    EnName: 'Nicaragua', Name: '尼加拉瓜', IOS2: 'NI', IOS3: 'NIC', Code: '505',
  },
  {
    EnName: 'Nepal',
    Name: '尼泊尔',
    IOS2: 'NP',
    IOS3: 'NPL',
    Code: '977',
  },
  {
    EnName: 'Niger', Name: '尼日尔', IOS2: 'NE', IOS3: 'NER', Code: '227',
  },
  {
    EnName: 'Nigeria',
    Name: '尼日利亚',
    IOS2: 'NG',
    IOS3: 'NGA',
    Code: '234',
  },
  {
    EnName: 'Niue', Name: '纽埃', IOS2: 'NU', IOS3: 'NIU', Code: '683',
  },
  {
    EnName: 'Norway',
    Name: '挪威',
    IOS2: 'NO',
    IOS3: 'NOR',
    Code: '47',
  },
  {
    EnName: 'Palau', Name: '帕劳', IOS2: 'PW', IOS3: 'PLW', Code: '680',
  },
  {
    EnName: 'Portugal',
    Name: '葡萄牙',
    IOS2: 'PT',
    IOS3: 'PRT',
    Code: '351',
  },
  {
    EnName: 'Japan', Name: '日本', IOS2: 'JP', IOS3: 'JPN', Code: '81',
  },
  {
    EnName: 'Sweden',
    Name: '瑞典',
    IOS2: 'SE',
    IOS3: 'SWE',
    Code: '46',
  },
  {
    EnName: 'Switzerland',
    Name: '瑞士',
    IOS2: 'CH',
    IOS3: 'CHE',
    Code: '41',
  },
  {
    EnName: 'El Salvador', Name: '萨尔瓦多', IOS2: 'SV', IOS3: 'SLV', Code: '503',
  },
  {
    EnName: 'Samoa',
    Name: '萨摩亚',
    IOS2: 'WS',
    IOS3: 'WSM',
    Code: '685',
  },
  {
    EnName: 'Serbia',
    Name: '塞尔维亚',
    IOS2: 'RS',
    IOS3: 'SRB',
    Code: '381',
  },
  {
    EnName: 'Sierra Leone',
    Name: '塞拉利昂',
    IOS2: 'SL',
    IOS3: 'SLE',
    Code: '232',
  },
  {
    EnName: 'Senegal', Name: '塞内加尔', IOS2: 'SN', IOS3: 'SEN', Code: '221',
  },
  {
    EnName: 'Cyprus',
    Name: '塞浦路斯',
    IOS2: 'CY',
    IOS3: 'CYP',
    Code: '357',
  },
  {
    EnName: 'Seychelles',
    Name: '塞舌尔',
    IOS2: 'SC',
    IOS3: 'SYC',
    Code: '248',
  },
  {
    EnName: 'Saudi Arabia',
    Name: '沙特阿拉伯',
    IOS2: 'SA',
    IOS3: 'SAU',
    Code: '966',
  },
  {
    EnName: 'Christmas Island',
    Name: '圣诞岛',
    IOS2: 'CX',
    IOS3: 'CXR',
    Code: '61',
  },
  {
    EnName: 'Sao Tome and Principe',
    Name: '圣多美和普林西比',
    IOS2: 'ST',
    IOS3: 'STP',
    Code: '239',
  },
  {
    EnName: 'Saint Helena',
    Name: '圣赫勒拿',
    IOS2: 'SH',
    IOS3: 'SHN',
    Code: '290',
  },
  {
    EnName: 'Saint Kitts and Nevis',
    Name: '圣基茨和尼维斯',
    IOS2: 'KN',
    IOS3: 'KNA',
    Code: '1869',
  },
  {
    EnName: 'Saint Lucia',
    Name: '圣卢西亚',
    IOS2: 'LC',
    IOS3: 'LCA',
    Code: '1758',
  },
  {
    EnName: 'San Marino',
    Name: '圣马力诺',
    IOS2: 'SM',
    IOS3: 'SMR',
    Code: '378',
  },
  {
    EnName: 'Saint Pierre and Miquelon',
    Name: '圣皮埃尔和密克隆',
    IOS2: 'PM',
    IOS3: 'SPM',
    Code: '508',
  },
  {
    EnName: 'Saint Vincent and the Grenadines',
    Name: '圣文森特和格林纳丁斯',
    IOS2: 'VC',
    IOS3: 'VCT',
    Code: '1784',
  },
  {
    EnName: 'Sri Lanka', Name: '斯里兰卡', IOS2: 'LK', IOS3: 'LKA', Code: '94',
  },
  {
    EnName: 'Slovakia',
    Name: '斯洛伐克',
    IOS2: 'SK',
    IOS3: 'SVK',
    Code: '421',
  },
  {
    EnName: 'Slovenia',
    Name: '斯洛文尼亚',
    IOS2: 'SI',
    IOS3: 'SVN',
    Code: '386',
  },
  {
    EnName: 'Svalbard and Jan Mayen',
    Name: '斯瓦尔巴特',
    IOS2: 'SJ',
    IOS3: 'SJM',
    Code: '47',
  },
  {
    EnName: 'Swaziland', Name: '斯威士兰', IOS2: 'SZ', IOS3: 'SWZ', Code: '268',
  },
  {
    EnName: 'Sudan',
    Name: '苏丹',
    IOS2: 'SD',
    IOS3: 'SDN',
    Code: '249',
  },
  {
    EnName: 'Suriname',
    Name: '苏里南',
    IOS2: 'SR',
    IOS3: 'SUR',
    Code: '597',
  },
  {
    EnName: 'Solomon Islands',
    Name: '所罗门群岛',
    IOS2: 'SB',
    IOS3: 'SLB',
    Code: '677',
  },
  {
    EnName: 'Somalia', Name: '索马里', IOS2: 'SO', IOS3: 'SOM', Code: '252',
  },
  {
    EnName: 'Tajikistan',
    Name: '塔吉克斯坦',
    IOS2: 'TJ',
    IOS3: 'TJK',
    Code: '992',
  },
  {
    EnName: 'Thailand', Name: '泰国', IOS2: 'TH', IOS3: 'THA', Code: '66',
  },
  {
    EnName: 'Tanzania',
    Name: '坦桑尼亚',
    IOS2: 'TZ',
    IOS3: 'TZA',
    Code: '255',
  },
  {
    EnName: 'Tonga',
    Name: '汤加',
    IOS2: 'TO',
    IOS3: 'TON',
    Code: '676',
  },
  {
    EnName: 'Turks and Caicos Islands',
    Name: '特克斯和凯科斯群岛',
    IOS2: 'TC',
    IOS3: 'TCA',
    Code: '1649',
  },
  {
    EnName: 'Trinidad and Tobago',
    Name: '特立尼达和多巴哥',
    IOS2: 'TT',
    IOS3: 'TTO',
    Code: '1868',
  },
  {
    EnName: 'Tunisia', Name: '突尼斯', IOS2: 'TN', IOS3: 'TUN', Code: '216',
  },
  {
    EnName: 'Tuvalu',
    Name: '图瓦卢',
    IOS2: 'TV',
    IOS3: 'TUV',
    Code: '688',
  },
  {
    EnName: 'Turkey', Name: '土耳其', IOS2: 'TR', IOS3: 'TUR', Code: '90',
  },
  {
    EnName: 'Turkmenistan',
    Name: '土库曼斯坦',
    IOS2: 'TM',
    IOS3: 'TKM',
    Code: '993',
  },
  {
    EnName: 'Tokelau',
    Name: '托克劳',
    IOS2: 'TK',
    IOS3: 'TKL',
    Code: '690',
  },
  {
    EnName: 'Wallis and Futuna',
    Name: '瓦利斯和富图纳群岛',
    IOS2: 'WF',
    IOS3: 'WLF',
    Code: '681',
  },
  {
    EnName: 'Vanuatu', Name: '瓦努阿图', IOS2: 'VU', IOS3: 'VUT', Code: '678',
  },
  {
    EnName: 'Guatemala',
    Name: '危地马拉',
    IOS2: 'GT',
    IOS3: 'GTM',
    Code: '502',
  },
  {
    EnName: 'Venezuela', Name: '委内瑞拉', IOS2: 'VE', IOS3: 'VEN', Code: '58',
  },
  {
    EnName: 'Brunei',
    Name: '文莱',
    IOS2: 'BN',
    IOS3: 'BRN',
    Code: '673',
  },
  {
    EnName: 'Uganda', Name: '乌干达', IOS2: 'UG', IOS3: 'UGA', Code: '256',
  },
  {
    EnName: 'Ukraine',
    Name: '乌克兰',
    IOS2: 'UA',
    IOS3: 'UKR',
    Code: '380',
  },
  {
    EnName: 'Uruguay', Name: '乌拉圭', IOS2: 'UY', IOS3: 'URY', Code: '598',
  },
  {
    EnName: 'Uzbekistan',
    Name: '乌兹别克斯坦',
    IOS2: 'UZ',
    IOS3: 'UZB',
    Code: '998',
  },
  {
    EnName: 'Spain',
    Name: '西班牙',
    IOS2: 'ES',
    IOS3: 'ESP',
    Code: '34',
  },
  {
    EnName: 'Western Sahara',
    Name: '西撒哈拉',
    IOS2: 'EH',
    IOS3: 'ESH',
    Code: '212',
  },
  {
    EnName: 'Greece', Name: '希腊', IOS2: 'GR', IOS3: 'GRC', Code: '30',
  },
  {
    EnName: 'Singapore',
    Name: '新加坡',
    IOS2: 'SG',
    IOS3: 'SGP',
    Code: '65',
  },
  {
    EnName: 'New Caledonia',
    Name: '新喀里多尼亚',
    IOS2: 'NC',
    IOS3: 'NCL',
    Code: '687',
  },
  {
    EnName: 'New Zealand', Name: '新西兰', IOS2: 'NZ', IOS3: 'NZL', Code: '64',
  },
  {
    EnName: 'Hungary',
    Name: '匈牙利',
    IOS2: 'HU',
    IOS3: 'HUN',
    Code: '36',
  },
  {
    EnName: 'Jamaica', Name: '牙买加', IOS2: 'JM', IOS3: 'JAM', Code: '1876',
  },
  {
    EnName: 'Armenia',
    Name: '亚美尼亚',
    IOS2: 'AM',
    IOS3: 'ARM',
    Code: '374',
  },
  {
    EnName: 'Yemen', Name: '也门', IOS2: 'YE', IOS3: 'YEM', Code: '967',
  },
  {
    EnName: 'Iraq',
    Name: '伊拉克',
    IOS2: 'IQ',
    IOS3: 'IRQ',
    Code: '964',
  },
  {
    EnName: 'Israel', Name: '以色列', IOS2: 'IL', IOS3: 'ISR', Code: '972',
  },
  {
    EnName: 'Italy',
    Name: '意大利',
    IOS2: 'IT',
    IOS3: 'ITA',
    Code: '39',
  },
  {
    EnName: 'India', Name: '印度', IOS2: 'IN', IOS3: 'IND', Code: '91',
  },
  {
    EnName: 'Indonesia',
    Name: '印度尼西亚',
    IOS2: 'ID',
    IOS3: 'IDN',
    Code: '62',
  },
  {
    EnName: 'United Kingdom',
    Name: '英国',
    IOS2: 'GB',
    IOS3: 'GBR',
    Code: '44',
  },
  {
    EnName: 'British Virgin Islands',
    Name: '英属维尔京群岛',
    IOS2: 'VG',
    IOS3: 'VGB',
    Code: '1284',
  },
  {
    EnName: 'British Indian Ocean Territory',
    Name: '英属印度洋领地',
    IOS2: 'IO',
    IOS3: 'IOT',
    Code: '246',
  },
  {
    EnName: 'Jordan', Name: '约旦', IOS2: 'JO', IOS3: 'JOR', Code: '962',
  },
  {
    EnName: 'Vietnam',
    Name: '越南',
    IOS2: 'VN',
    IOS3: 'VNM',
    Code: '84',
  },
  {
    EnName: 'Zambia', Name: '赞比亚', IOS2: 'ZM', IOS3: 'ZMB', Code: '260',
  },
  {
    EnName: 'Chad',
    Name: '乍得',
    IOS2: 'TD',
    IOS3: 'TCD',
    Code: '235',
  },
  {
    EnName: 'Gibraltar', Name: '直布罗陀', IOS2: 'GI', IOS3: 'GIB', Code: '350',
  },
  {
    EnName: 'Chile',
    Name: '智利',
    IOS2: 'CL',
    IOS3: 'CHL',
    Code: '56',
  },
  {
    EnName: 'Mainland China',
    Name: '中国大陆',
    IOS2: 'CN',
    IOS3: 'CHN',
    Code: '86',
  },
  {
    EnName: 'Hong Kong, China',
    Name: '中国香港',
    IOS2: 'HK',
    IOS3: 'HKG',
    Code: '852',
  },
  {
    EnName: 'Macau, China',
    Name: '中国澳门',
    IOS2: 'MO',
    IOS3: 'MAC',
    Code: '853',
  },
  {
    EnName: 'Taiwan, China',
    Name: '中国台湾',
    IOS2: 'TW',
    IOS3: 'TWN',
    Code: '886',
  },
  {
    EnName: 'Central African Republic', Name: '中非共和国', IOS2: 'CF', IOS3: 'CAF', Code: '236',
  },
];
